export const END_POINTS = {
  EQUIPMENTS: 'equipments',
  CHEER_STYLES: 'cheer-styles',
  CHEER_TYPES: 'cheer-types',
  MEASUREMENT_UNITS: 'measurement/measurement-unit',
  ROLES: 'roles',
  USERS: 'users',
  USERS_ME: 'users/me',
  USERS_PROFILE: 'users/profile',

  USERS_FORGOT_PASSWORD: 'users/forgot-password',
  USERS_RESET_PASSWORD: 'users/reset-password',
  SIGNUP: 'users/signup',
  AUTH_LOGIN: 'auth/login',
  AUTH_LOGIN_SOCIAL: 'auth/social-login',
  AUTH_LOGIN_TWITTER: 'auth/twitter/login',
  EXERCISES: 'cardio/exercises',
  CARDIO_CREATE: 'cardio/session',
  RPE: 'cardio/rpes',

  // billing and subscription
  SUBSCRIPTION_PLANS: 'plans',
  SUBSCRIPTION_CANCEL: 'stripe/cancel-subscription',
  SUBSCRIPTION_SUBSCRIBE_PLAN: 'stripe/create-subscription-session',
  SUBSCRIPTION_CHANGE: 'stripe/change-plan',
  BILLING_HISTORY: 'users/billing-history',
  VALIDATE_PROMOTION_CODE: 'stripe/validate-promotion-code',
  WEEKLY_SUMMARY: 'cardio/past-training/weekly-summary',
  WEEKLY_WORKOUTS: 'cardio/past-training/weekly-workouts',
  PERFORMANCE_METRICS: 'cardio/past-training/performance-metrics',

  //Measurements
  MEASUREMENTS: 'measurement/measurement-list',
  ATHLETE_MEASUREMENTS: 'measurement/coach-student/get-all-student-by-coach-code',
  CREATE_MEASUREMENTS: 'measurement/measurement-session',
  BASES_SPOTTER: 'measurement/bases',
  FLYER: 'measurement/flyers',
  LATEST_RESULT: 'measurement/athlete-latest-result',
  IMPROVEMENT: 'measurement/athlete-improved-result',
  LAST_THREE_MONTHS: 'measurement/athlete-last-3-months',
  THREE_LATEST_RESULTS: 'measurement/athlete-three-latest-results',
  RESULT_FOR_ALL_MEASUREMENTS: 'measurement/athlete-latest-result-for-all-measurements',
};
