export const END_POINTS = {
  EQUIPMENTS: 'equipments',
  CHEER_STYLES: 'cheer-styles',
  CHEER_TYPES: 'cheer-types',
  ROLES: 'roles',
  USERS: 'users',
  USERS_ME: 'users/me',
  USERS_FORGOT_PASSWORD: 'users/forgot-password',
  USERS_RESET_PASSWORD: 'users/reset-password',
  SIGNUP: 'users/signup',
  AUTH_LOGIN: 'auth/login',
  AUTH_LOGIN_SOCIAL: 'auth/social-login',
  AUTH_LOGIN_TWITTER: 'auth/twitter/login',
  WEEKLY_SUMMARY: 'cardio/past-training/weekly-summary',
  EXERCISES: 'cardio/exercises',
  CARDIO_CREATE: 'cardio/session',
  RPE: 'cardio/rpes',
};
