export const ROUTES = {
  WELCOME: 'welcome',
  HOME: 'home',
  SIGNUP: 'signup',
  LOGIN: 'login',
  PROFILE: 'profile',
  PRIVACY: 'privacy',
  TERMS_AND_CONDITIONS: 'terms-and-conditions',
  ABOUT_US: 'about-us',
  TRAINING: 'training',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  TRAINING_STRENGTH: 'training/strength',
  TRAINING_STRENGTH_NEW: 'training/strength/new',
  TRAINING_STRENGTH_PROGRAM: 'training/strength/program',
  TRAINING_STRENGTH_EXERCISE: 'training/strength/program/:id/exercise',
  TRAINING_CARDIO: 'training/cardio',
  TRAINING_TEAM_TRAINING_LOG: 'training/team-training-log',
  MEASUREMENT: 'measurement',
  MEASUREMENT_NEW: 'measurement/new',
  MEASUREMENT_TEAM_DATA: 'measurement/team-data',
  HIT_MISS: 'hit-miss',
  HIT_MISS_ROUTINES: 'hit-miss/routines',
  HIT_MISS_ROUTINES_NEW: 'hit-miss/routines/new',
  HIT_MISS_REPORT: 'hit-miss/report',
  HIT_MISS_DATA: 'hit-miss/data',
  BILLING_AND_SUBSCRIPTION: 'billing-and-subscription',
  CHECK_OFF: 'check-off',
  CHECK_OFF_NEW: 'check-off/new',
  CHECK_OFF_REVIEW: 'check-off/review',
  CHECK_OFF_TEAM_DATA: 'check-off/team-data',
};

export const WHITE_LIST = [
  `/${ROUTES.TERMS_AND_CONDITIONS}`,
  `/${ROUTES.ABOUT_US}`,
  `/${ROUTES.PRIVACY}`,
];
